version: '3'
services:
  app:
    image: bestplaces-image
    container_name: bestplaces-container
    restart: always
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234567
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_DATABASE: bestplaces
    volumes:
        - C:\Users\thai0\Documents\dumps:/docker-entrypoint-initdb.d


